### ISSUE TITLE
When do you release the codebase?

### ISSUE THREAD

**Issue by hongge831** [dluvizon/deephar#1]
@dluvizon Hi, I am interested in your work on pose estimation and action recognition, so when do you release your code?  hhah

**Comment by nukadelic** [comment]
+1

**Comment by dluvizon** [comment]
Hello, please accept my apologies for the long delay.
It will be released in a few days, I am working to make everything portable and easy to use.

**Comment by nukadelic** [comment]
Thanks, you are a legend !

**Comment by griffinpup** [comment]
Hey, following up on this topic. It looks like most/all of the code is now uploaded, would that be correct?

**Comment by dihuangcode** [comment]
Hello, will you release your train code in the near future?

**Comment by dluvizon** [comment]
Yes, I can do that in two weeks =D

**Comment by hongge831** [comment]
@dluvizon hello, I want to know where is the soft_argmax implementation in your codebase, I am a new guy about this filed, would you mind telling me where the soft_argmax is?

**Comment by dluvizon** [comment]
Hi @hongge831 , the soft-argmax is implemented by function `build_softargmax_2d` in file `deephar/models/blocks.py`.

**Comment by victoriamazo** [comment]
Hi! When do you release the weights?

**Comment by dluvizon** [comment]
Hi @victoriamazo ,
Trained weights are already released.

**Comment by yuvaramsingh94** [comment]
Hi dluvizon . can i know where to find the training code for this work
