### ISSUE TITLE
Testing my own videos ?

### ISSUE THREAD

**Issue by basicvisual** [dluvizon/deephar#13]
Hi , I wanted to test it against my own set of videos , stored locally on the PC. Is it possible to do so ??

**Comment by dluvizon** [comment]
Probably, once you preload the data correctly and the semantics are the same.

**Comment by patrickESM** [comment]
thank you  @dluvizon.

Really nice work you did here!

I also am interested to run it against my own set of videos. Can you maybe help us a little bit more with the semantics you addressed in you previews reply?

Thank you again!

**Comment by dluvizon** [comment]
Hi @patrickESM ,
The action dataset on which this method was trained involve sports activities ([PennAction](https://dreamdragon.github.io/PennAction/)) or daily activities ([NTU RGB+D](http://rose1.ntu.edu.sg/datasets/actionrecognition.asp)).
Therefore, the weights provided here are restricted to the semantics of these datasets.
For a different scenario, you'll need to re-train the model.
