### ISSUE TITLE
Multiple skeletons

### ISSUE THREAD

**Issue by nshreyasvi** [dluvizon/deephar#16]
Hello,
I wanted to know if it works with multiple skeletons and can it visualise them in 3 dimensions based on relative distance of the skeletons ?

**Comment by dluvizon** [comment]
Hi @nshreyasvi ,
Not, it predicts only a single person in the bounding box.

**Comment by nshreyasvi** [comment]
Hello @dluvizon,
If there is a presence of 2 or more people in the video, will it detect the same person throughout time or can the skeletal tracking change from person to person as well?

**Comment by dluvizon** [comment]
Hi,
This method is a single-frame pose estimator, not a person tracking. In general, it detects the person that is closer to the center of the image.
So, to answer your question, it can possibly change from person to person across frames.
