### ISSUE TITLE
Not Utilizing A Video

### ISSUE THREAD

**Issue by victor-gz** [dluvizon/deephar#18]
I noticed that the following sequence does not exist when creating the image dataset using your provided code: a02_s11_e02_c01. 

It should be a simple fix of adding the following line to vid2jpeg.txt:
S11/Videos/Directions.54138969.mp4:a02_s11_e02_c01

**Comment by victor-gz** [comment]
I missed it the first time, but it appears the annotations for this video are also missing. Is there a reason for this?

**Comment by dluvizon** [comment]
Hi @vgonzalez88 ,
These videos / labels are probably missing because they are corrupted or missing the original dataset.
It has been a long time that the data was pre-processed, so I'm not sure.
But you can check it in the original dataset: http://vision.imar.ro/human3.6m/description.php
