### ISSUE TITLE
Example Video of system in action?

### ISSUE THREAD

**Issue by Kingbadger3d** [dluvizon/deephar#2]
Hi, A few questions: 1. Is the code released on here complete yet, and what AI framework does it use 2: Could this be used to train a pose e.g person with arm raised to ask a question and then have the recognizer work on multiple people in cam footage or video and add counting of persons in view with that action (arm raised).3: Could you provide a video of the tool in action.4: could the system also recognize multiple people in the same footage doing different actions.

Many thanks, J

**Comment by satyaborg** [comment]
Hello dluvizon,
I echo Kingbadger3d's sentiment on this. Can you provide a brief gif or demo of the implementation?
Also could you add a few notes about what libraries and frameworks were used along with the key difference in terms of algorithm or advantages that is different from other existing pose estimation implementations?
Looking forward to running this!

Regards.

**Comment by dluvizon** [comment]
Hi @Kingbadger3d , 1) the code is not completely released yet. When released, I will indicate by closing #1 . It is based on Keras and TensforFlow.
2) This software works for a single person only, and actions are trained accordingly to two datasets: PennAction and NTU RGB+D. For that specific action you'll need to retrain / fine-tune the model with appropriately data. 3) There is no script / code ready for that, but it could be implemented easily. 4) No.

**Comment by dluvizon** [comment]
Hi @SyBorg91 , sure, I'll do that in the next few days.
Thanks for your advise.
