### ISSUE TITLE
Weight for your model

### ISSUE THREAD

**Issue by xiaxx244** [dluvizon/deephar#20]
Can you upload your pretrained model's weight? Thanks!

**Comment by dluvizon** [comment]
Hi @xiaxx244 ,

They are already available! If you check, for example, the evaluation script for MPI (https://github.com/dluvizon/deephar/blob/master/exp/mpii/eval_mpii_singleperson.py), the code downloads the weights file from github.

**Comment by xiaxx244** [comment]
Thanks for responding.
