### ISSUE TITLE
Where can I get the additional annotation of the NTU RGB+D dataset?

### ISSUE THREAD

**Issue by jin-miao-cai** [dluvizon/deephar#21]
Hellow, Sir!

Firstly, thank you for your open source !!

I'm now doing a research project on the NTU RGB+D dataset. In my previous study, I have the [the additional annotation](https://drive.google.com/file/d/1eTJPb8q2XCRK8NEC4h17p17JW2DDNwjG/view) provided in this project.

Since there is a new version of NTU RGB+D dataset, namly "NTU RGB+D 120",  I also want to use the additional annotation information in the experiment on"NTU RGB+D 120". But I just can not find the download link in the official website of '[NTU RGB+D](http://rose1.ntu.edu.sg/datasets/actionrecognition.asp)'. 

So, How can I get this the additional annotation from the raw provided data?

Thank you for your attention to this matter.

**Comment by dluvizon** [comment]
Hi @jin-miao-cai ,
I don't have this annotation for the NTU RGB+D 120.
If it has the same original annotation as the NTU RGB+D 60 dataset, you could compute the pose labels by taking the (x,y) in the image coordinates and concatenating it with the depth information in each point. To recover the depth information in each point, you could sample the depth map at the position (x, y).
