### ISSUE TITLE
TypeError: lin_interpolation_2d() got an unexpected keyword argument 'dim'

### ISSUE THREAD

**Issue by kmamine** [dluvizon/deephar#22]
Hi , 
I'm trying to use the build_softargmax_2d block in my own network, 

but when compiling the model i get the following error 

`---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-16-ccc465365375> in <module>()
----> 1 model = get_model()
      2 model.summary()

1 frames

<ipython-input-13-2051ee9b018c> in get_model()
     19     num_rows, num_cols, num_filters = K.int_shape(x)[1:]
     20     sams_input_shape = (num_rows, num_cols, num_filters)
---> 21     sam_model = build_softargmax_2d(sams_input_shape, rho=0, name='sSAM')
     22     sam_model.summary()
     23     output = sam_model(x)

/content/deephar/deephar/models/blocks.py in build_softargmax_2d(input_shape, rho, name)
    316         x = kl_divergence_regularizer(x, rho=rho)
    317 
--> 318     x_x = lin_interpolation_2d(x, dim=0)
    319     x_y = lin_interpolation_2d(x, dim=1)
    320     x = concatenate([x_x, x_y])

TypeError: lin_interpolation_2d() got an unexpected keyword argument 'dim'`

I traced the error like this 
blocks.py --> build_softargmax_2d(....)  --> x_x = lin_interpolation_2d(x, dim=0) [line 318]
while  in layers.py -->lin_interpolation_2d(x, axis, vmin=0., vmax=1., name=None) [the function signature ]. 
How  to fix this ?

**Comment by PhenomenalOnee** [comment]
Replace "dim" with "axis"

**Comment by patrickESM** [comment]
thank you @PhenomenalOnee 

can confirm that this works!

**Comment by dluvizon** [comment]
This was also fixed in the source code. Thanks @PhenomenalOnee !
