### ISSUE TITLE
Weights for predict bboxes on NTU

### ISSUE THREAD

**Issue by hammb** [dluvizon/deephar#29]
Where can I find the weights needed in the predict_bboxes.py script for the NTU dataset?
(weights_posebaseline_060.hdf5)

**Comment by dluvizon** [comment]
Hi @hammb , I'm trying to recover this file from my old backups... as soon as I have it, I'll make the file available.

**Comment by dluvizon** [comment]
Hi @hammb , the weights for bbox prediction will not be made publicly available, but I can share it with you if really needed. In that case, please send me an email requesting it.
Thanks
