### ISSUE TITLE
No weights provided for the multitask models

### ISSUE THREAD

**Issue by hammb** [dluvizon/deephar#30]
Dear @dluvizon 
I was able to reproduce your results with the merge models, but not with both multitask models (eval_ntu_multitask.py and eval_penn_multitask.py), because I could not find the needed weights for those models ("weights_mpii+penn_ar_028.hdf5" and "weights_3dp+ntu_ar_030.hdf5"). I tried to load the weights from the releases, which were uploaded for the merge models from 2018, but the multitask models performed really bad with them. Could you please upload the weights for the multitask models? 
Thank you!

**Kinect V2 livetest on  2018 merge model pose estimation (eval_ntu_ar_pe_merge.py)**
![pose_beineueberkreuzt](https://user-images.githubusercontent.com/48390954/80467244-d5ba7b00-893d-11ea-82ec-b7126fee30d8.PNG)

**Kinect V2 livetest on new multi-task model (All joints predicted to point in the middle of the image) (eval_ntu_multitask.py) used weight from 2018 release**
![Action Recognition](https://user-images.githubusercontent.com/48390954/80467222-d18e5d80-893d-11ea-8938-ef80c87ba892.PNG)

**Kinect V2 livetest on  2018 merge model action recognition (eval_ntu_ar_pe_merge.py)**
![taking a selfie](https://user-images.githubusercontent.com/48390954/80467801-a48e7a80-893e-11ea-84a8-2d8b907362c0.PNG)

**Didn't upload Kinect V2 livetest action recognition on new multi-task model because it is just randomly choosing one class**

**Comment by happyyqt** [comment]
Hi, I think 'weights_mpii+penn_ar_028.hdf5' is the weights by running'train_penn_multimodel'. But when I run this file, it requires a pre-trained weight'weights_mpii+penn_ar_007.hdf5' ..... Any ideas?

**Comment by dluvizon** [comment]
Hi,
The file "weights_mpii+penn_ar_028.hdf5" is now public at: https://drive.google.com/file/d/106yIhqNN-TrI34SX81q2xbU-NczcQj6I/view?usp=sharing
Please check the README (it was updated) for running the evaluation script. It also requires a file with predicted bounding boxes  for PennAction: https://drive.google.com/file/d/1qXpEKF0d9KxmQdd2_QSIA1c3WGj1D3Y3/view?usp=sharing

I'll try to update the code and publish the weights for NTU soon.

**Comment by dluvizon** [comment]
Hi, the weights are available at https://drive.google.com/file/d/1I6GftXEkL5nohLA60Vi6faW0rvTZg6Kx/view?usp=sharing
