### ISSUE TITLE
question about displaying output of pose estimation, action recognition

### ISSUE THREAD

**Issue by dradnats-kim** [dluvizon/deephar#32]
hello, I'm student studying about computer vision and deep learning.

I'm in trouble about displaying output.

I could get log text of eval program.

but I want to display pose into image and action labeling ....

I searched Issues but I couldn't solve...

I'm sorry about this stupid question.

thank you.

**Comment by happyyqt** [comment]
I wanna see a 3d coordinate system like in the paper as well.  Maybe using a 3d tool like Open3D or PCL? I am not sure what tool the author used.
