### ISSUE TITLE
a quick demo for action recognition

### ISSUE THREAD

**Issue by dandingol03** [dluvizon/deephar#37]
Hi, thanks for your amazing work ! I was wandering is there an quick demo for action recognition, or how can i use the pre - trained model to predict an action from a series of images or video

**Comment by nirjhar-das** [comment]
Are the pre-trained weights available in this repo?

**Comment by dandingol03** [comment]
Yes,the pre-trained model of the eval_penn_multitask i can get. But the script seems like blocked on my machine.
I run the script on the google colab, and here is the output as below:
``
2020-12-13 09:48:41.461262: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-13 09:48:42.539611: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10

``
  It is blocked for nearly half an hour.

**Comment by dandingol03** [comment]
Yes, the pre-trained model is available. However, i want to get some visual output like an jpg with some predicted boxes on it, something like that.

**Comment by dluvizon** [comment]
Hi @dandingol03 ,

Unfortunately, I don't have feature implemented and I'm not planning to implement in soon.
But I guess that it is something relatively easy to do for video clips.

**Comment by dandingol03** [comment]
thanks for your apply~
