### ISSUE TITLE
penn action provided weights can't be load with keras 

### ISSUE THREAD

**Issue by AtousaTorabi** [dluvizon/deephar#5]

**Comment by AtousaTorabi** [comment]
It seems the weight you have provided is not correctly saved I get similar issues to load as this one:
https://github.com/keras-team/keras/issues/10428

it seems when you save weights for combined model "joints" "visual" this problem happens. Could you please verify the weight you provided?

**Comment by dluvizon** [comment]
Hi @AtousaTorabi ,
It should work fine with Keras version 2.1.4, which was the version used for training.
