### ISSUE TITLE
General question with resepect to paper

### ISSUE THREAD

**Issue by YuktiADY** [dluvizon/deephar#56]
Hello,

I read your paper its really interesting work and good .

How can we  train the pose estimation and action network ? Can we train pose and action network seperately.
Does action recognition takes input as 2d or 3 pose or both ?

Because my training dataset contains only 3 action and evaluation has to be on dataset which has 16 actions ?

My aim is to estimate 3d pose and action recogntion.

**Comment by dluvizon** [comment]
Hi @YuktiADY ,
Thank you! In our first method (CVPR), pose and action parts can be trained separated, or jointly (fine-tuning). In our TPAMI paper, to train the action part, the pose part has to be trained before (pre-trained) or jointly.
The action recognition part takes as input 3D poses as (u, v, relative_d).
You can adapt the model to the number of classes that you have in your dataset. The model has to be changed.
