### ISSUE TITLE
Run it in real time & action recognition 

### ISSUE THREAD

**Issue by intvo** [dluvizon/deephar#6]
1- How can i run this code in real time using my webcam camera as you did in the video? 
2- Can you add text to each action which tells if the person is walking, sitting...
Thank you

**Comment by dluvizon** [comment]
1- You have to implement your front-end for that, to capture frames from your camera predict poses / actions using the pre-trained model. With a good GPU it should work relatively fast.
2- You can use the labels given by the dataset (PennAction or NTU), so then you replace the action output by the corresponding text.

**Comment by arpit-kapoor** [comment]
Hi @dluvizon,

Could you please provide an example or a brief explanation on how to use the 3d pose estimation model to predict the pose from any given image? And, what preprocessing and postprocessing would be required for obtaining the 3d pose from the pre-trained model?

Thanks!

**Comment by dluvizon** [comment]
Hi @arpit-kapoor ,

There is an evaluation script that does that [link](https://github.com/dluvizon/deephar/blob/master/exp/h36m/eval_h36m.py).
Basically, you have to:
  1. Crop your frame around the person
  2. Resize it to 256x256 and normalize pixel values to [-1,1]
  3. Pass through the model
  4. Select the predicted output (usually the last is the better), which is a vector with shape (num_batches, num_joints, 3)
  5. Project the normalized prediction to the image, considering the cropping region that you selected

Predicted poses are normalized in x-y by the image crop, from (0,0) top-left corner to (1,1) bottom-right. The depth (z) is normalized from [0,1] considering a 2 meters range, centered on the root joint.

**Comment by arpit-kapoor** [comment]
Hi @dluvizon,
Thanks for the reply. I ran the model for single image, available [here](https://imgur.com/a/qICIYVz).
I tried plotting the results from the model and found that the x,y were pretty decent, while the z values were a little messed up. 
The result could be found [here](https://imgur.com/a/1YxYt8F).
Could I be doing something wrong?
