### ISSUE TITLE
Error 2D pose estimation

### ISSUE THREAD

**Issue by NguyenDangBinh** [dluvizon/deephar#8]
dear all,
I have error when I run       python exp/mpii/eval_mpii_singleperson.py output/eval-mpii     on anaconda prompt. How to fix it?

(deephar-master) D:\Binh\deephar-master> python exp/mpii/eval_mpii_singleperson.py output/eval-mpii
Initializing deephar v.0.4.1
Traceback (most recent call last):
  File "exp/mpii/eval_mpii_singleperson.py", line 8, in <module>
    import deephar
  File "D:\Binh\deephar-master\deephar\__init__.py", line 16, in <module>
    keras_git = os.environ.get('HOME') + '/git/fchollet/keras'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by dluvizon** [comment]
This seems a python issue related to Windows. The software should work fine on linux systems, but I never tried on Windows.
